# permissions for end users to edit charlesdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: charlesdeployment-editor-role
rules:
- apiGroups:
  - io.charlescd.my.domain
  resources:
  - charlesdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - io.charlescd.my.domain
  resources:
  - charlesdeployments/status
  verbs:
  - get
